export const REGISTER_POST_SUCCESS="REGISTER_POST_SUCCESS";
export const REGISTER_POST_FAIL="REGISTER_POST_FAIL";
export const REGISTER_POST_REQUEST="REGISTER_POST_REQUEST";

export const ALL_POST_SUCCESS="ALL_POST_SUCCESS";
export const ALL_POST_FAIL="ALL_POST_FAIL";
export const ALL_POST_REQUEST="ALL_POST_REQUEST";


export const USER_POST_SUCCESS="USER_POST_SUCCESS";
export const USER_POST_FAIL="USER_POST_FAIL";
export const USER_POST_REQUEST="USER_POST_REQUEST";

export const POST_SUCCESS="POST_SUCCESS";
export const POST_FAIL="POST_FAIL";
export const POST_REQUEST="POST_REQUEST";

export const DELETE_POST_SUCCESS="DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL="DELETE_POST_FAIL";
export const DELETE_POST_REQUEST="DELETE_POST_REQUEST";