export const POST_SUB_REQUEST="POST_SUB_REQUEST";
export const POST_SUB_SUCCESS="POST_SUB_SUCCESS";
export const POST_SUB_FAIL="POST_SUB_FAIL";

export const GET_SUB_REQUEST="GET_SUB_REQUEST";
export const GET_SUB_SUCCESS="GET_SUB_SUCCESS";
export const GET_SUB_FAIL="GET_SUB_FAIL";


export const USER_SUB_REQUEST="USER_SUB_REQUEST";
export const USER_SUB_SUCCESS="USER_SUB_SUCCESS";
export const USER_SUB_FAIL="USER_SUB_FAIL";

export const ALL_SUB_REQUEST="ALL_SUB_REQUEST";
export const ALL_SUB_SUCCESS="ALL_SUB_SUCCESS";
export const ALL_SUB_FAIL="ALL_SUB_FAIL";

export const ACCEPTED_SUB_REQUEST="ACCEPTED_SUB_REQUEST";
export const ACCEPTED_SUB_SUCCESS="ACCEPTED_SUB_SUCCESS";
export const ACCEPTED_SUB_FAIL="ACCEPTED_SUB_FAIL";

export const ACCEPT_SUB_REQUEST="ACCEPT_SUB_REQUEST";
export const ACCEPT_SUB_SUCCESS="ACCEPT_SUB_SUCCESS";
export const ACCEPT_SUB_FAIL="ACCEPT_SUB_FAIL";

export const DELETE_SUB_REQUEST="DELETE_SUB_REQUEST";
export const DELETE_SUB_SUCCESS="DELETE_SUB_SUCCESS";
export const DELETE_SUB_FAIL="DELETE_SUB_FAIL";